import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();

	// Ensure publish/<plugin-id> directory exists and copy release artifacts
	try {
		const manifestPath = path.resolve(process.cwd(), 'manifest.json');
		let pluginId = 'plugin';
		if (fs.existsSync(manifestPath)) {
			try {
				const manifestRaw = fs.readFileSync(manifestPath, 'utf8');
				const manifest = JSON.parse(manifestRaw);
				if (manifest && manifest.id) pluginId = String(manifest.id);
			} catch (e) {
				console.warn('Failed to read/parse manifest.json for publish folder name', e);
			}
		}
		const publishDir = path.resolve(process.cwd(), 'publish', pluginId);
		if (!fs.existsSync(publishDir)) fs.mkdirSync(publishDir, { recursive: true });
		// copy main.js and manifest.json; styles.css is optional
		const assets = ['main.js', 'manifest.json', 'styles.css'];
		for (const a of assets) {
			const src = path.resolve(process.cwd(), a);
			const dest = path.resolve(publishDir, a);
			if (fs.existsSync(src)) {
				fs.copyFileSync(src, dest);
				console.log(`Copied ${a} -> publish/${pluginId}/${a}`);
			}
		}
	} catch (e) {
		console.error('Failed to write publish directory', e);
	}

	process.exit(0);
} else {
	await context.watch();
}
